# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9853659a0d4b6ea41a747d0b01f78ab516d386d6e1464032ea8af615b0c36df0a727bcf80b081ef351c81bfc61a55425ee309e981414643e3eae97b4aba68959

test:
  secret_key_base: 9ef2d34ab0e87782695d5af203965dea260146a9e46d77150f9ca8eaa10c97092eb5959a941f1abc530cb76c74cbf4e3930d10cea5611b07bcf8c818c6059457

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
